### ISSUE TITLE
Remove script dependecies and install them instead

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#14]
- [ ] remove bootstrap script in public\index.html
- [ ] install bootstrap via npm

package-json should show dependencies
dependencies should be installed on local machine by using the npm install command
(node_modules will stay on local machine leave part of .gitignore)

**Comment by chaitanya-24** [comment]
Hello @TimA314, I would like to solve this.

**Comment by TimA314** [comment]
> Hello @TimA314, I would like to solve this.

Hi unfortunately this was actually just solved. This project is still in its infancy and has so much work to do. If you know of something you would like to work on feel free to post an issue and assign yourself. I will continue to post more issues in the future!
