### ISSUE TITLE
Need a navbar for navigation.

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#2]
Using bootstrap component would be easy. The navbar will need eventually need a drop down that can list to routes in the project folder.

**Comment by AniketRajSingh** [comment]
I want to work on this Issue, can you assign it to me.

**Comment by ash1895-web** [comment]
Can I work on this issue?

**Comment by TimA314** [comment]
> Can I work on this issue?

Absolutely! I will assign the issue to you.
