### ISSUE TITLE
Add dark and light mode theme

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#24]
Would be nice if there was a toggle button in or near the navbar that toggles themes or for now just background color and font.

**Comment by nitin094-hub** [comment]
Could you plz assign this task to me?

**Comment by TimA314** [comment]
Sure! Let me know if you have any questions

**Comment by nitin094-hub** [comment]
Can I use this package: https://www.npmjs.com/package/react-dark-mode-toggle

**Comment by nitin094-hub** [comment]
and can I use the redux toolkit?

**Comment by TimA314** [comment]
Yes redux toolkit would be helpful and that package looks like it would be a nice button to use

**Comment by nitin094-hub** [comment]
alright

**Comment by nitin094-hub** [comment]
how should I contribute now?

**Comment by ritiksaxena124** [comment]
Yes, first make a new branch then make a pull request.  This is a good practice.
