### ISSUE TITLE
Need a better tutorial on Home Page

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#3]
It would be nice if there was a better tutorial on the home page on how to get started (clone repo through -> submiting a pull request). This could alternitevly be a link to a new page that shows a tutorial.

**Comment by codyconway77** [comment]
I made a slightly more detailed tutorial to Home.js and added dependacy react-markdown to display said tutorial in markdown format. Tell me what you think.

**Comment by codyconway77** [comment]
#4 My pull request

**Comment by codyconway77** [comment]
> I made a slightly more detailed tutorial to Home.js and added dependacy react-markdown to display said tutorial in markdown format. Tell me what you think.

Would look much better if I was able to figure out how to display the images smaller.

**Comment by TimA314** [comment]
> > I made a slightly more detailed tutorial to Home.js and added dependacy react-markdown to display said tutorial in markdown format. Tell me what you think.
> 
> Would look much better if I was able to figure out how to display the images smaller.
> 

It's a great start! Let's close this issue and create another issue with more specific improvements that we can make👍
