### ISSUE TITLE
React Button Tutorial needs CSS

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#41]
The reactButtonTutorial needs  some design.

**Comment by ritiksaxena124** [comment]
go ahead brother, I have assigned this task to you.

**Comment by ritiksaxena124** [comment]
Hey @emiacerbi you did a great job. I have a suggestion, wrap the whole code of reactButtonTutorial in a container 'div' and instead of giving styling to the whole body, give that styling to that container div.

**Comment by emiacerbi** [comment]
Sure I'll do it as soon as I can!
