### ISSUE TITLE
Home page structure and design

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#6]
Home page could use some design. Such as centering content adding margins, and maybe a background. 

Up for a challenge: How about a button that switches the font and backround from dark to light mode.

**Comment by nitin094-hub** [comment]
Can i work on this issue?

**Comment by TimA314** [comment]
> Can i work on this issue?

Absolutely! I will assign you to the task. Feel free to comment here or in the discussion Q&A if you have any trouble or questions.

**Comment by nitin094-hub** [comment]
where should i make a css file?

**Comment by TimA314** [comment]
> where should i make a css file?

you can place a new Home.css file in the pages folder next to Home.js

**Comment by TimA314** [comment]
The page looks really good and there were no conflicts! I will close this issue. If you have any feature ideas feel free to sumbit an issue and you can add yourself if you'd like to tackle it. Thanks for your contribution!
