### ISSUE TITLE
Add Learning or example section

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground#8]
A nice feature would be to have a section or page that provides links to tutorials or examples. Example resources could be react tutorials, code snippets, blogs, ect. 

Challenge: Make a page with a step by step tutorial on something and list it in the new tutorials section.

**Comment by ritiksaxena124** [comment]
can I work on this issue?

**Comment by TimA314** [comment]
> can I work on this issue?

Sure! I will assign the task to you. Feel free to respond here or in the discussions if you have any questions or concerns. 

Also keep in mind there are people working on the home page so it may be a good idea to make this a component of its own and we can place it on the homepage where appropriate. Otherwise feel free to create however you like.
